name: zaarvis_ai
description: A personal AI assistant built by Shojib Parvez.
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^6.1.0
  flutter_tts: ^3.6.3
  avatar_glow: ^2.0.2
  animated_text_kit: ^4.2.2
  lottie: ^2.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
dev_dependencies:
  integration_test:
    sdk: flutter
